import type { WelfareService, WelfareData } from "./types";

/** API 키 없을 때 사용하는 샘플 데이터 */
export const SAMPLE_WELFARE_SERVICES: WelfareService[] = [
  {
    id: "WLF00001",
    name: "기초생활보장 생계급여",
    summary: "생활이 어려운 저소득층에게 일상생활에 필요한 급여를 지급하여 최저생활을 보장합니다.",
    category: "생활안정",
    targetGroup: "저소득",
    department: "보건복지부",
    applyMethod: "주민센터 방문 또는 복지로 온라인 신청",
    url: "https://www.bokjiro.go.kr",
  },
  {
    id: "WLF00002",
    name: "기초연금",
    summary: "만 65세 이상 소득하위 70% 어르신에게 매월 최대 334,810원을 지급합니다.",
    category: "생활안정",
    targetGroup: "노인",
    department: "보건복지부",
    applyMethod: "주민센터 또는 국민연금공단 지사 방문 신청",
  },
  {
    id: "WLF00003",
    name: "아동수당",
    summary: "만 8세 미만(0~95개월) 아동에게 매월 10만원을 지급합니다.",
    category: "생활안정",
    targetGroup: "아동",
    department: "보건복지부",
    applyMethod: "주민센터 방문 또는 복지로·정부24 온라인 신청",
  },
  {
    id: "WLF00004",
    name: "청년월세 한시 특별지원",
    summary: "저소득 독립 청년(만 19~34세)에게 월 최대 20만원의 월세를 지원합니다.",
    category: "주거",
    targetGroup: "청년",
    department: "국토교통부",
    applyMethod: "복지로 온라인 신청",
  },
  {
    id: "WLF00005",
    name: "주거급여",
    summary: "중위소득 48% 이하 가구에 임차료(전·월세) 또는 수선유지비를 지원합니다.",
    category: "주거",
    targetGroup: "저소득",
    department: "국토교통부",
    applyMethod: "주민센터 방문 신청",
  },
  {
    id: "WLF00006",
    name: "국가장학금 (I·II유형)",
    summary: "소득수준에 연계하여 대학생에게 등록금 범위 내 장학금을 지원합니다.",
    category: "교육",
    targetGroup: "청년",
    department: "교육부",
    applyMethod: "한국장학재단 홈페이지 온라인 신청",
  },
  {
    id: "WLF00007",
    name: "국민취업지원제도",
    summary: "취업을 원하는 사람에게 취업지원서비스와 생활안정 지원(구직촉진수당)을 제공합니다.",
    category: "고용",
    targetGroup: "청년",
    department: "고용노동부",
    applyMethod: "고용센터 방문 또는 고용24 온라인 신청",
  },
  {
    id: "WLF00008",
    name: "장애인연금",
    summary: "중증장애인에게 매월 최대 403,180원을 지급하여 생활 안정을 지원합니다.",
    category: "생활안정",
    targetGroup: "장애인",
    department: "보건복지부",
    applyMethod: "주민센터 방문 신청",
  },
  {
    id: "WLF00009",
    name: "한부모가족 아동양육비",
    summary: "저소득 한부모가족의 만 18세 미만 아동에게 월 20만원의 양육비를 지원합니다.",
    category: "생활안정",
    targetGroup: "한부모",
    department: "여성가족부",
    applyMethod: "주민센터 방문 신청",
  },
  {
    id: "WLF00010",
    name: "의료급여",
    summary: "생활이 어려운 저소득 국민에게 의료비를 지원하여 국민 건강을 보장합니다.",
    category: "건강",
    targetGroup: "저소득",
    department: "보건복지부",
    applyMethod: "주민센터 방문 신청",
  },
  {
    id: "WLF00011",
    name: "영유아 보육료 지원",
    summary: "어린이집을 이용하는 만 0~5세 영유아에게 보육료를 지원합니다.",
    category: "교육",
    targetGroup: "아동",
    department: "보건복지부",
    applyMethod: "아이사랑 포털 또는 주민센터 신청",
  },
  {
    id: "WLF00012",
    name: "부모급여",
    summary: "만 0~1세 아동을 양육하는 부모에게 매월 최대 100만원을 지급합니다.",
    category: "생활안정",
    targetGroup: "임산부",
    department: "보건복지부",
    applyMethod: "주민센터 방문 또는 복지로 온라인 신청",
  },
  {
    id: "WLF00013",
    name: "긴급복지지원",
    summary: "갑작스러운 위기상황(실직, 질병 등)에 처한 가구에 긴급 생계·의료·주거비를 지원합니다.",
    category: "생활안정",
    targetGroup: "저소득",
    department: "보건복지부",
    applyMethod: "시군구청 또는 129 전화 신청",
  },
  {
    id: "WLF00014",
    name: "청년도약계좌",
    summary: "만 19~34세 청년이 매월 최대 70만원 납입 시 정부가 지원금을 더해줍니다.",
    category: "생활안정",
    targetGroup: "청년",
    department: "금융위원회",
    applyMethod: "은행 앱에서 가입 신청",
  },
  {
    id: "WLF00015",
    name: "실업급여",
    summary: "비자발적으로 이직한 근로자에게 구직활동 기간 동안 급여를 지급합니다.",
    category: "고용",
    targetGroup: "직장인",
    department: "고용노동부",
    applyMethod: "고용센터 방문 또는 고용24 온라인 신청",
  },
  {
    id: "WLF00016",
    name: "노인일자리 및 사회활동 지원",
    summary: "만 60세 이상 어르신에게 다양한 사회활동과 일자리 기회를 제공합니다.",
    category: "고용",
    targetGroup: "노인",
    department: "보건복지부",
    applyMethod: "시니어클럽·노인복지관 방문 또는 지자체 접수",
  },
  {
    id: "WLF00017",
    name: "장애인 활동지원",
    summary: "만 6세 이상 65세 미만 등록 장애인에게 활동보조, 방문목욕, 방문간호를 지원합니다.",
    category: "건강",
    targetGroup: "장애인",
    department: "보건복지부",
    applyMethod: "주민센터 방문 신청",
  },
  {
    id: "WLF00018",
    name: "첫만남이용권",
    summary: "출생아에게 200만원(첫째) 또는 300만원(둘째 이상) 바우처를 지급합니다.",
    category: "생활안정",
    targetGroup: "임산부",
    department: "보건복지부",
    applyMethod: "행정복지센터 또는 정부24 온라인 신청",
  },
  {
    id: "WLF00019",
    name: "국민건강보험 본인부담 상한제",
    summary: "연간 건강보험 본인부담금이 상한액 초과 시 초과분을 환급해 줍니다.",
    category: "건강",
    targetGroup: "직장인",
    department: "보건복지부",
    applyMethod: "자동 적용 (초과분 환급)",
  },
  {
    id: "WLF00020",
    name: "문화누리카드",
    summary: "기초생활수급자·차상위 가구에게 1인당 연 13만원의 문화·여행·체육 이용권을 지급합니다.",
    category: "문화",
    targetGroup: "저소득",
    department: "문화체육관광부",
    applyMethod: "주민센터 방문 또는 문화누리카드 홈페이지 신청",
  },
  {
    id: "WLF00021",
    name: "보훈급여금",
    summary: "국가유공자 및 유족에게 보상금·수당 등 보훈급여를 지급합니다.",
    category: "생활안정",
    targetGroup: "국가유공자",
    department: "국가보훈부",
    applyMethod: "보훈(지)청 방문 신청",
  },
  {
    id: "WLF00022",
    name: "청년내일저축계좌",
    summary: "일하는 저소득 청년(중위소득 50~100%)이 3년간 매월 10만원 적립 시 정부 매칭 지원.",
    category: "생활안정",
    targetGroup: "청년",
    department: "보건복지부",
    applyMethod: "복지로 온라인 신청",
  },
  {
    id: "WLF00023",
    name: "고용보험 미적용자 출산급여",
    summary: "고용보험 미가입 여성(프리랜서, 자영업자 등)에게 출산 시 150만원을 지급합니다.",
    category: "건강",
    targetGroup: "임산부",
    department: "고용노동부",
    applyMethod: "고용센터 방문 또는 고용24 신청",
  },
  {
    id: "WLF00024",
    name: "에너지바우처",
    summary: "취약계층 가구에 냉·난방 에너지 비용을 바우처로 지원합니다.",
    category: "생활안정",
    targetGroup: "저소득",
    department: "산업통상자원부",
    applyMethod: "주민센터 방문 신청",
  },
];

export function getSampleWelfareData(): WelfareData {
  return {
    services: SAMPLE_WELFARE_SERVICES,
    totalCount: SAMPLE_WELFARE_SERVICES.length,
    updatedAt: new Date().toISOString(),
    isLive: false,
  };
}
