import type { RatesData, RateProduct } from "./types";

const sampleDeposits: RateProduct[] = [
  {
    bankName: "KB국민은행",
    productName: "KB Star 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.15,
    maxRate: 3.15,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.25,
    maxRate: 3.25,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.10,
    maxRate: 3.10,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 36,
    baseRate: 3.05,
    maxRate: 3.05,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.20,
    maxRate: 3.20,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.30,
    maxRate: 3.30,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.15,
    maxRate: 3.15,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 36,
    baseRate: 3.05,
    maxRate: 3.05,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 정기예금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 6,
    baseRate: 3.10,
    maxRate: 3.10,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 정기예금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 12,
    baseRate: 3.25,
    maxRate: 3.25,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 정기예금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 24,
    baseRate: 3.10,
    maxRate: 3.10,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 정기예금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 36,
    baseRate: 3.00,
    maxRate: 3.00,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.10,
    maxRate: 3.10,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.20,
    maxRate: 3.20,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.05,
    maxRate: 3.05,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 정기예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 36,
    baseRate: 2.95,
    maxRate: 2.95,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.20,
    maxRate: 3.20,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.30,
    maxRate: 3.30,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.10,
    maxRate: 3.10,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 36,
    baseRate: 3.00,
    maxRate: 3.00,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 정기예금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.30,
    maxRate: 3.30,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 정기예금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.40,
    maxRate: 3.40,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 정기예금",
    joinWay: "스마트폰",
    saveTerm: 24,
    baseRate: 3.20,
    maxRate: 3.20,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "토스뱅크",
    productName: "토스뱅크 정기예금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.40,
    maxRate: 3.40,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "토스뱅크",
    productName: "토스뱅크 정기예금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.50,
    maxRate: 3.50,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 정기예금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.35,
    maxRate: 3.35,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 정기예금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.45,
    maxRate: 3.45,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 정기예금",
    joinWay: "스마트폰",
    saveTerm: 24,
    baseRate: 3.25,
    maxRate: 3.25,
    rateType: "단리",
    specialCondition: "",
    joinDeny: "제한없음",
  },
  {
    bankName: "IBK기업은행",
    productName: "IBK 평생한가족통장",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 6,
    baseRate: 3.15,
    maxRate: 3.35,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "IBK기업은행",
    productName: "IBK 평생한가족통장",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 12,
    baseRate: 3.25,
    maxRate: 3.45,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "IBK기업은행",
    productName: "IBK 평생한가족통장",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 24,
    baseRate: 3.10,
    maxRate: 3.30,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "SC제일은행",
    productName: "e-그린세이브 예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.25,
    maxRate: 3.45,
    rateType: "단리",
    specialCondition: "디지털 채널 가입 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "SC제일은행",
    productName: "e-그린세이브 예금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.35,
    maxRate: 3.55,
    rateType: "단리",
    specialCondition: "디지털 채널 가입 시 우대",
    joinDeny: "제한없음",
  },
];

const sampleSavings: RateProduct[] = [
  {
    bankName: "KB국민은행",
    productName: "KB Star 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.30,
    maxRate: 4.30,
    rateType: "단리",
    specialCondition: "KB Star 멤버십 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.50,
    maxRate: 4.50,
    rateType: "단리",
    specialCondition: "KB Star 멤버십 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.30,
    maxRate: 4.20,
    rateType: "단리",
    specialCondition: "KB Star 멤버십 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "KB국민은행",
    productName: "KB Star 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 36,
    baseRate: 3.20,
    maxRate: 4.00,
    rateType: "단리",
    specialCondition: "KB Star 멤버십 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.40,
    maxRate: 4.40,
    rateType: "단리",
    specialCondition: "쏠 앱 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.55,
    maxRate: 4.55,
    rateType: "단리",
    specialCondition: "쏠 앱 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "신한은행",
    productName: "쏠편한 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.35,
    maxRate: 4.25,
    rateType: "단리",
    specialCondition: "쏠 앱 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 적금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 6,
    baseRate: 3.25,
    maxRate: 4.25,
    rateType: "단리",
    specialCondition: "하나원큐 가입 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 적금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 12,
    baseRate: 3.45,
    maxRate: 4.45,
    rateType: "단리",
    specialCondition: "하나원큐 가입 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "하나은행",
    productName: "하나 적금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 24,
    baseRate: 3.25,
    maxRate: 4.15,
    rateType: "단리",
    specialCondition: "하나원큐 가입 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.20,
    maxRate: 4.20,
    rateType: "단리",
    specialCondition: "우리WON뱅킹 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.40,
    maxRate: 4.40,
    rateType: "단리",
    specialCondition: "우리WON뱅킹 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "우리은행",
    productName: "WON 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.20,
    maxRate: 4.10,
    rateType: "단리",
    specialCondition: "우리WON뱅킹 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.35,
    maxRate: 4.35,
    rateType: "단리",
    specialCondition: "올원뱅크 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.50,
    maxRate: 4.50,
    rateType: "단리",
    specialCondition: "올원뱅크 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "NH농협은행",
    productName: "NH올원e적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 24,
    baseRate: 3.30,
    maxRate: 4.20,
    rateType: "단리",
    specialCondition: "올원뱅크 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 자유적금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.50,
    maxRate: 4.00,
    rateType: "단리",
    specialCondition: "자유납입",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 자유적금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.60,
    maxRate: 4.10,
    rateType: "단리",
    specialCondition: "자유납입",
    joinDeny: "제한없음",
  },
  {
    bankName: "카카오뱅크",
    productName: "카카오뱅크 자유적금",
    joinWay: "스마트폰",
    saveTerm: 24,
    baseRate: 3.40,
    maxRate: 3.90,
    rateType: "단리",
    specialCondition: "자유납입",
    joinDeny: "제한없음",
  },
  {
    bankName: "토스뱅크",
    productName: "토스뱅크 적금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.60,
    maxRate: 4.60,
    rateType: "단리",
    specialCondition: "첫 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "토스뱅크",
    productName: "토스뱅크 적금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.70,
    maxRate: 4.70,
    rateType: "단리",
    specialCondition: "첫 가입 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 적금",
    joinWay: "스마트폰",
    saveTerm: 6,
    baseRate: 3.55,
    maxRate: 4.55,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 적금",
    joinWay: "스마트폰",
    saveTerm: 12,
    baseRate: 3.65,
    maxRate: 4.65,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "케이뱅크",
    productName: "코드K 적금",
    joinWay: "스마트폰",
    saveTerm: 24,
    baseRate: 3.45,
    maxRate: 4.35,
    rateType: "단리",
    specialCondition: "급여이체 시 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "IBK기업은행",
    productName: "IBK D-Day적금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 6,
    baseRate: 3.30,
    maxRate: 4.30,
    rateType: "단리",
    specialCondition: "급여이체+카드실적 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "IBK기업은행",
    productName: "IBK D-Day적금",
    joinWay: "인터넷,스마트폰,영업점",
    saveTerm: 12,
    baseRate: 3.45,
    maxRate: 4.45,
    rateType: "단리",
    specialCondition: "급여이체+카드실적 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "SC제일은행",
    productName: "마이줌 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 6,
    baseRate: 3.45,
    maxRate: 4.45,
    rateType: "단리",
    specialCondition: "디지털 전용 우대",
    joinDeny: "제한없음",
  },
  {
    bankName: "SC제일은행",
    productName: "마이줌 적금",
    joinWay: "인터넷,스마트폰",
    saveTerm: 12,
    baseRate: 3.55,
    maxRate: 4.55,
    rateType: "단리",
    specialCondition: "디지털 전용 우대",
    joinDeny: "제한없음",
  },
];

export function getSampleData(): RatesData {
  return {
    deposits: sampleDeposits,
    savings: sampleSavings,
    updatedAt: new Date().toISOString(),
    isLive: false,
  };
}
